[package]
name = "ethp2p-broadcast"
description = "Erasure-coded broadcast engine and pluggable strategies for ethp2p."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ethp2p-protocol = { path = "../ethp2p-protocol" }
prost = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
reed-solomon-erasure = { workspace = true }
sha2 = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "rt", "rt-multi-thread", "test-util"] }
serde = { workspace = true }
serde_yaml = { workspace = true }
hex = { workspace = true }
