//! Reed-Solomon broadcast strategy.
//!
//! Implements `specs/003-ec-broadcast-rs.md`. The submodules cover:
//!
//! - [`encode`] — origin encoding (payload → preamble + shards)
//! - [`verify`] — synchronous per-chunk SHA-256 verification
//! - [`decode`] — k-of-n reconstruction with end-to-end integrity
//! - [`planner`] — emit planner (allocation-ordered min-heap)
//! - [`state`] — per-session strategy state container
//!
//! The on-wire types (`Preamble`, `ChunkIdent`) live in
//! [`crate::pb::rs`] and are generated by `prost-build` from the
//! vendored `proto/rs.proto`.

pub mod decode;
pub mod encode;
pub mod planner;
pub mod state;
pub mod verify;

/// SHA-256 digest size in bytes.
pub const HASH_LEN: usize = 32;
